### ISSUE TITLE
Feature Request: Terragrunt support

### ISSUE THREAD

**Issue by ghost** [getindata/terraform-null-atlantis-repo-config#17]
Hello there ;) 

Would it be possible to get a feature-flagged Terragrunt config in the future as well, since Terragrunt is a popular TF-wrapper?
https://www.runatlantis.io/docs/custom-workflows.html#terragrunt

**Comment by moss2k13** [comment]
i think this is what you want:
https://github.com/transcend-io/terragrunt-atlantis-config
